"""Add activa to clases

Revision ID: 130ada31982f
Revises: decf52653843
Create Date: 2026-09-03 17:41:18.056982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130ada31982f'
down_revision: Union[str, None] = 'decf52653843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clases', sa.Column('activa', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clases', 'activa')
    # ### end Alembic commands ###
