"""Agregada nueva columna en Archivo

Revision ID: a5a0ffe9a306
Revises: 
Create Date: 2026-08-18 22:14:53.969576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5a0ffe9a306'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivos', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.alter_column('archivos', 'clase_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('usuarios', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuarios', 'ultimo_aviso_global_id',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'ultimo_aviso_global_id',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('usuarios', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('archivos', 'clase_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('archivos', 'size_bytes')
    # ### end Alembic commands ###
